# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'URExampleWeatherView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URExampleWeatherView
  pod 'URWeatherView'
  # pod 'GoogleMaps'

  target 'URExampleWeatherViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'URExampleWeatherViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
